"project_id": "651448"
"api_token": "2d5765b137f41a478dbddd9764b57514ccd405397dee6981ea3fce10694b1064017c73f1beb40268"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "src/main/resources/lang/en_US.json",
    "translation": "src/main/resources/lang/%locale_with_underscore%.json",
    "dest": "/blocko/game_translation.json"
  }
]
