name: Blocko
version: 1.0
api-version: "1.21.4"
main: net.spacetivity.blocko.Blocko
description: A "Mensch Ärgere dich nicht! / Ludo" clone in Minecraft
website: wiki.spacetivity.net
commands:
  blocko:
  arenainvite:
author:
  - TGamings
depend:
  - SpaceDependencies
  - SpaceInventories
